language: go

env:
  - DEP_VERSION="X.X.X"

go:
  - 1.9.x
  - tip

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure
  
  script:
    - go vet ./...
    - go test -v ./openid
